use sha2::{Digest, Sha256};
use std::collections::HashMap;
use std::fs;
use std::path::{Path, PathBuf};
use anyhow::{bail, Context, Result};
use walkdir::WalkDir;

pub struct SpecFreezeGuard {
    spec_files: Vec<PathBuf>,
    hashes: HashMap<PathBuf, [u8; 32]>,
    original_permissions: HashMap<PathBuf, fs::Permissions>,
    active: bool,
}

impl SpecFreezeGuard {
    /// Discover all .sysml files under spec_dir and prepare the guard (does not activate yet)
    pub fn new(spec_dir: &Path) -> Result<Self> {
        let spec_files: Vec<PathBuf> = WalkDir::new(spec_dir)
            .into_iter()
            .filter_map(|e| e.ok())
            .filter(|e| e.path().extension().map(|x| x == "sysml").unwrap_or(false))
            .map(|e| e.path().to_path_buf())
            .collect();

        if spec_files.is_empty() {
            bail!("No .sysml files found under {:?}", spec_dir);
        }

        Ok(SpecFreezeGuard {
            spec_files,
            hashes: HashMap::new(),
            original_permissions: HashMap::new(),
            active: false,
        })
    }

    /// Activate the freeze: compute hashes and set all spec files read-only
    pub fn activate(&mut self) -> Result<()> {
        tracing::info!("Activating spec freeze for {} files", self.spec_files.len());

        for path in &self.spec_files {
            // Store original permissions for restoration
            let meta = fs::metadata(path)
                .with_context(|| format!("Cannot stat {:?}", path))?;
            self.original_permissions.insert(path.clone(), meta.permissions());

            // Compute SHA-256
            let hash = sha256_file(path)
                .with_context(|| format!("Cannot hash {:?}", path))?;
            self.hashes.insert(path.clone(), hash);

            // Set read-only
            let mut perms = meta.permissions();
            perms.set_readonly(true);
            fs::set_permissions(path, perms)
                .with_context(|| format!("Cannot set {:?} read-only", path))?;

            tracing::debug!("Frozen: {:?} ({})", path, hex::encode(hash));
        }

        self.active = true;
        Ok(())
    }

    /// Verify all spec files still match their recorded hashes.
    /// Call this after every agent iteration.
    pub fn verify_integrity(&self) -> Result<()> {
        if !self.active {
            return Ok(());
        }

        for (path, expected) in &self.hashes {
            let actual = sha256_file(path)
                .with_context(|| format!("Cannot re-hash {:?}", path))?;

            if actual != *expected {
                bail!(
                    "SPEC TAMPER DETECTED: {:?} was modified during generation.\n\
                     Expected SHA-256: {}\n\
                     Actual SHA-256:   {}\n\
                     Aborting to protect specification integrity.",
                    path,
                    hex::encode(expected),
                    hex::encode(actual)
                );
            }
        }

        Ok(())
    }

    /// Deactivate: restore original file permissions
    pub fn deactivate(&mut self) -> Result<()> {
        if !self.active {
            return Ok(());
        }

        for (path, perms) in &self.original_permissions {
            fs::set_permissions(path, perms.clone())
                .with_context(|| format!("Cannot restore permissions on {:?}", path))?;
        }

        self.active = false;
        tracing::info!("Spec freeze deactivated, permissions restored");
        Ok(())
    }

    /// Returns the list of spec file paths (for inclusion in .gooseignore)
    pub fn spec_files(&self) -> &[PathBuf] {
        &self.spec_files
    }
}

impl Drop for SpecFreezeGuard {
    fn drop(&mut self) {
        if self.active {
            tracing::warn!("SpecFreezeGuard dropped while active — restoring permissions");
            let _ = self.deactivate();
        }
    }
}

fn sha256_file(path: &Path) -> Result<[u8; 32]> {
    let content = fs::read(path)?;
    let mut hasher = Sha256::new();
    hasher.update(&content);
    Ok(hasher.finalize().into())
}

/// Generate .gooseignore content to prevent Goose from accessing spec files
pub fn generate_gooseignore(spec_dir: &Path) -> String {
    format!(
        "# Auto-generated by sysgen — DO NOT EDIT\n\
         # Spec files are read-only inputs. The agent MUST NOT modify them.\n\
         {}/**/*.sysml\n\
         {}/**/*.kerml\n",
        spec_dir.display(),
        spec_dir.display()
    )
}

/// Write .gooseignore to the project root
pub fn write_gooseignore(project_root: &Path, spec_dir: &Path) -> Result<()> {
    let content = generate_gooseignore(spec_dir);
    let path = project_root.join(".gooseignore");
    fs::write(&path, content)
        .with_context(|| format!("Cannot write {:?}", path))?;
    tracing::debug!("Wrote .gooseignore at {:?}", path);
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    fn write_sysml(dir: &TempDir, name: &str, content: &str) -> PathBuf {
        let p = dir.path().join(name);
        fs::write(&p, content).unwrap();
        p
    }

    #[test]
    fn activate_makes_files_readonly() {
        let dir = TempDir::new().unwrap();
        write_sysml(&dir, "spec.sysml", "package A {}");

        let mut guard = SpecFreezeGuard::new(dir.path()).unwrap();
        guard.activate().unwrap();

        // File should be read-only
        let meta = fs::metadata(dir.path().join("spec.sysml")).unwrap();
        assert!(meta.permissions().readonly());

        guard.deactivate().unwrap();
    }

    #[test]
    fn deactivate_restores_permissions() {
        let dir = TempDir::new().unwrap();
        write_sysml(&dir, "spec.sysml", "package A {}");

        let mut guard = SpecFreezeGuard::new(dir.path()).unwrap();
        guard.activate().unwrap();
        guard.deactivate().unwrap();

        // Should be writable again
        fs::write(dir.path().join("spec.sysml"), "package B {}").unwrap();
    }

    #[test]
    fn detects_tamper() {
        let dir = TempDir::new().unwrap();
        let path = write_sysml(&dir, "spec.sysml", "package A {}");

        let mut guard = SpecFreezeGuard::new(dir.path()).unwrap();
        guard.activate().unwrap();

        // Temporarily make writable to simulate tamper
        let mut perms = fs::metadata(&path).unwrap().permissions();
        perms.set_readonly(false);
        fs::set_permissions(&path, perms).unwrap();
        fs::write(&path, "package TAMPERED {}").unwrap();

        let result = guard.verify_integrity();
        assert!(result.is_err());
        assert!(result.unwrap_err().to_string().contains("SPEC TAMPER DETECTED"));
    }

    #[test]
    fn verify_integrity_passes_when_unchanged() {
        let dir = TempDir::new().unwrap();
        write_sysml(&dir, "spec.sysml", "package A {}");

        let mut guard = SpecFreezeGuard::new(dir.path()).unwrap();
        guard.activate().unwrap();

        assert!(guard.verify_integrity().is_ok());

        guard.deactivate().unwrap();
    }

    #[test]
    fn new_fails_when_no_sysml_files() {
        let dir = TempDir::new().unwrap();
        let result = SpecFreezeGuard::new(dir.path());
        assert!(result.is_err());
    }

    #[test]
    fn generate_gooseignore_contains_spec_dir() {
        let dir = TempDir::new().unwrap();
        let content = generate_gooseignore(dir.path());
        let dir_str = dir.path().to_string_lossy().to_string();
        assert!(content.contains(&dir_str));
        assert!(content.contains("*.sysml"));
        assert!(content.contains("*.kerml"));
    }

    #[test]
    fn write_gooseignore_creates_file() {
        let dir = TempDir::new().unwrap();
        let spec_dir = TempDir::new().unwrap();
        write_gooseignore(dir.path(), spec_dir.path()).unwrap();
        let gooseignore = dir.path().join(".gooseignore");
        assert!(gooseignore.exists());
        let content = fs::read_to_string(&gooseignore).unwrap();
        assert!(content.contains("Auto-generated by sysgen"));
    }
}
