use anyhow::{bail, Context, Result};
use std::fs;
use std::path::Path;

#[derive(clap::Args)]
pub struct InitCommand {
    /// Path to initialise (defaults to current directory)
    #[arg(default_value = ".")]
    pub path: std::path::PathBuf,
}

impl InitCommand {
    pub fn run(self) -> Result<()> {
        let project_dir = &self.path;

        if project_dir.exists() {
            // Allow init into an existing empty directory, bail if non-empty
            let is_empty = project_dir
                .read_dir()
                .with_context(|| format!("Cannot read directory {:?}", project_dir))?
                .next()
                .is_none();
            if !is_empty {
                bail!(
                    "Directory {:?} already exists and is not empty",
                    project_dir
                );
            }
        }

        let project_name = project_dir
            .file_name()
            .and_then(|n| n.to_str())
            .unwrap_or("project");
        let pascal_name = to_pascal_case(project_name);

        // Create directory structure
        fs::create_dir_all(project_dir.join("spec"))
            .with_context(|| format!("Failed to create spec/ under {:?}", project_dir))?;
        fs::create_dir_all(project_dir.join("src"))
            .with_context(|| format!("Failed to create src/ under {:?}", project_dir))?;

        // Write all template files
        write_file(
            project_dir,
            "Cargo.toml",
            &cargo_toml_template(project_name),
        )?;
        write_file(project_dir, ".gitignore", "/target\n.sysgen/\n")?;
        write_file(project_dir, ".gooseignore", &gooseignore_template())?;
        write_file(
            project_dir,
            "spec/requirements.sysml",
            &spec_template(project_name, &pascal_name),
        )?;
        write_file(project_dir, "src/lib.rs", lib_rs_template())?;

        println!("Created SysGen project: {}", project_name);
        println!();
        println!("Next steps:");
        println!("  1. cd {}", project_dir.display());
        println!("  2. Edit spec/requirements.sysml to define your requirements");
        println!("  3. Set your LLM API key: export ANTHROPIC_API_KEY=your_key");
        println!("  4. Run: sysgen gen");

        Ok(())
    }
}

fn to_pascal_case(s: &str) -> String {
    s.split(['-', '_', ' '])
        .map(|word| {
            let mut chars = word.chars();
            match chars.next() {
                None => String::new(),
                Some(f) => f.to_uppercase().collect::<String>() + chars.as_str(),
            }
        })
        .collect()
}

fn write_file(dir: &Path, name: &str, content: &str) -> Result<()> {
    let path = dir.join(name);
    fs::write(&path, content).with_context(|| format!("Failed to write {:?}", path))
}

fn cargo_toml_template(name: &str) -> String {
    format!(
        r#"[package]
name = "{name}"
version = "0.1.0"
edition = "2021"

[dependencies]
sysgen-macros = {{ git = "https://github.com/gaarutyunov/sysgen", package = "sysgen-macros" }}
"#
    )
}

fn spec_template(project_name: &str, pascal_name: &str) -> String {
    format!(
        r#"// {project_name} Requirements
// Edit this file to define your system requirements.
// Run `sysgen gen` to generate implementation code.
package {pascal_name}Requirements {{
    private import ScalarValues::*;

    // Example requirement — edit or replace
    requirement def <'R1'> ExampleRequirement {{
        doc /* Replace this with your actual requirement description.
             * The system shall... */
    }}
}}
"#
    )
}

fn lib_rs_template() -> &'static str {
    "// This file is managed by sysgen.\n\
     // Add #[implements(\"RequirementName\")] to your implementation items.\n\
     // Add #[verifies(\"RequirementName\")] to your test functions.\n\
     use sysgen_macros::{implements, verifies};\n"
}

/// Spec files are intentionally NOT excluded here — the agent must be able to read
/// them to understand requirements. Protection against modification is enforced at
/// the OS level by `SpecFreezeGuard` (sets files read-only during `sysgen gen`).
fn gooseignore_template() -> String {
    "# Auto-generated by sysgen init\n\
     # Build artifacts and sysgen internals — the agent does not need these\n\
     /target\n\
     .sysgen/\n"
        .to_string()
}

#[cfg(test)]
mod tests {
    use super::*;
    use tempfile::TempDir;

    #[test]
    fn to_pascal_case_handles_hyphens() {
        assert_eq!(to_pascal_case("my-project"), "MyProject");
    }

    #[test]
    fn to_pascal_case_handles_underscores() {
        assert_eq!(to_pascal_case("my_project"), "MyProject");
    }

    #[test]
    fn to_pascal_case_handles_spaces() {
        assert_eq!(to_pascal_case("my project"), "MyProject");
    }

    #[test]
    fn to_pascal_case_single_word() {
        assert_eq!(to_pascal_case("project"), "Project");
    }

    #[test]
    fn init_creates_expected_files() {
        let tmp = TempDir::new().unwrap();
        let project_dir = tmp.path().join("my-project");

        let cmd = InitCommand {
            path: project_dir.clone(),
        };
        cmd.run().unwrap();

        assert!(project_dir.join("Cargo.toml").exists());
        assert!(project_dir.join(".gitignore").exists());
        assert!(project_dir.join(".gooseignore").exists());
        assert!(project_dir.join("spec/requirements.sysml").exists());
        assert!(project_dir.join("src/lib.rs").exists());
    }

    #[test]
    fn init_fails_if_dir_non_empty() {
        let tmp = TempDir::new().unwrap();
        // Create a file in the temp dir to make it non-empty
        fs::write(tmp.path().join("existing.txt"), "hello").unwrap();

        let cmd = InitCommand {
            path: tmp.path().to_path_buf(),
        };
        let result = cmd.run();
        assert!(result.is_err());
        assert!(result
            .unwrap_err()
            .to_string()
            .contains("already exists and is not empty"));
    }

    #[test]
    fn cargo_toml_contains_project_name() {
        let content = cargo_toml_template("foo-bar");
        assert!(content.contains("name = \"foo-bar\""));
        assert!(content.contains("sysgen-macros"));
    }

    #[test]
    fn spec_template_uses_pascal_name() {
        let content = spec_template("my-project", "MyProject");
        assert!(content.contains("MyProjectRequirements"));
        assert!(content.contains("my-project Requirements"));
    }

    #[test]
    fn gooseignore_does_not_exclude_spec() {
        let content = gooseignore_template();
        assert!(!content.contains("spec/"));
        assert!(content.contains("/target"));
        assert!(content.contains(".sysgen/"));
    }

    #[test]
    fn init_succeeds_in_empty_existing_dir() {
        let tmp = TempDir::new().unwrap();
        let cmd = InitCommand {
            path: tmp.path().to_path_buf(),
        };
        // Empty existing directory should be fine
        cmd.run().unwrap();
        assert!(tmp.path().join("Cargo.toml").exists());
    }
}
